/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package manwhalegends;

import manwhalegends.login;
/**
 *
 * @author Resty
 */
public class landing extends javax.swing.JFrame {

    /**
     * Creates new form landing
     */
    public landing() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LandingPNLBlack = new javax.swing.JPanel();
        ManwhalegendsLogo = new javax.swing.JLabel();
        Title3 = new javax.swing.JLabel();
        Title1 = new javax.swing.JLabel();
        Title2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        LandingPNLWhite = new javax.swing.JPanel();
        CatchDesc1 = new javax.swing.JLabel();
        CatchDesc3 = new javax.swing.JLabel();
        CatchDesc2 = new javax.swing.JLabel();
        CatchDesc4 = new javax.swing.JLabel();
        IntroDesc3 = new javax.swing.JLabel();
        IntroDesc = new javax.swing.JLabel();
        IntroDesc2 = new javax.swing.JLabel();
        SignUpLanding = new javax.swing.JPanel();
        SignUpRegister = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        GetStarted = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        RegisterLanding = new javax.swing.JPanel();
        SignUpRegister1 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LandingPNLBlack.setBackground(new java.awt.Color(0, 0, 0));
        LandingPNLBlack.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ManwhalegendsLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/manwhalegends.png"))); // NOI18N
        ManwhalegendsLogo.setOpaque(true);
        LandingPNLBlack.add(ManwhalegendsLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, 100));

        Title3.setFont(new java.awt.Font("Palatino Linotype", 3, 36)); // NOI18N
        Title3.setForeground(new java.awt.Color(255, 255, 255));
        Title3.setText("Repeat.");
        LandingPNLBlack.add(Title3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 130, -1));

        Title1.setFont(new java.awt.Font("Palatino Linotype", 3, 36)); // NOI18N
        Title1.setForeground(new java.awt.Color(255, 255, 255));
        Title1.setText("Click.");
        LandingPNLBlack.add(Title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, -1, -1));

        Title2.setFont(new java.awt.Font("Palatino Linotype", 3, 36)); // NOI18N
        Title2.setForeground(new java.awt.Color(255, 255, 255));
        Title2.setText("Read.");
        LandingPNLBlack.add(Title2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, -1, -1));
        LandingPNLBlack.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 120, 10));
        LandingPNLBlack.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 90, 10));
        LandingPNLBlack.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 90, 10));

        getContentPane().add(LandingPNLBlack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 440));

        LandingPNLWhite.setBackground(new java.awt.Color(255, 255, 255));
        LandingPNLWhite.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CatchDesc1.setBackground(new java.awt.Color(0, 0, 0));
        CatchDesc1.setFont(new java.awt.Font("Palatino Linotype", 3, 24)); // NOI18N
        CatchDesc1.setText("\"Your  ");
        LandingPNLWhite.add(CatchDesc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 30));

        CatchDesc3.setBackground(new java.awt.Color(0, 0, 0));
        CatchDesc3.setFont(new java.awt.Font("Palatino Linotype", 3, 20)); // NOI18N
        CatchDesc3.setText("mind   grows   bigger");
        LandingPNLWhite.add(CatchDesc3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 210, 30));

        CatchDesc2.setBackground(new java.awt.Color(0, 0, 0));
        CatchDesc2.setFont(new java.awt.Font("Palatino Linotype", 3, 20)); // NOI18N
        CatchDesc2.setText("imaginary and creative");
        LandingPNLWhite.add(CatchDesc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 210, 30));

        CatchDesc4.setBackground(new java.awt.Color(0, 0, 0));
        CatchDesc4.setFont(new java.awt.Font("Palatino Linotype", 3, 20)); // NOI18N
        CatchDesc4.setText("and   brighter   here!\"");
        LandingPNLWhite.add(CatchDesc4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 200, 30));

        IntroDesc3.setText("start your adventure today !");
        LandingPNLWhite.add(IntroDesc3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 280, 30));

        IntroDesc.setText("Manwha Legends is full of exciting stories that make");
        LandingPNLWhite.add(IntroDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 270, 30));

        IntroDesc2.setText("you dream, feel, and explore. Open a chapter and");
        LandingPNLWhite.add(IntroDesc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 270, 30));

        SignUpLanding.setBackground(new java.awt.Color(0, 0, 0));
        SignUpLanding.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SignUpLanding.setForeground(new java.awt.Color(255, 255, 255));
        SignUpLanding.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignUpLandingMouseClicked(evt);
            }
        });

        SignUpRegister.setFont(new java.awt.Font("Palatino Linotype", 3, 18)); // NOI18N
        SignUpRegister.setForeground(new java.awt.Color(255, 255, 255));
        SignUpRegister.setText(" Login");
        SignUpRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SignUpRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignUpRegisterMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout SignUpLandingLayout = new javax.swing.GroupLayout(SignUpLanding);
        SignUpLanding.setLayout(SignUpLandingLayout);
        SignUpLandingLayout.setHorizontalGroup(
            SignUpLandingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignUpLandingLayout.createSequentialGroup()
                .addComponent(SignUpRegister)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        SignUpLandingLayout.setVerticalGroup(
            SignUpLandingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SignUpLandingLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(SignUpRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        LandingPNLWhite.add(SignUpLanding, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 60, 30));
        LandingPNLWhite.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 320, 20));

        GetStarted.setBackground(new java.awt.Color(0, 0, 0));
        GetStarted.setFont(new java.awt.Font("Palatino Linotype", 3, 24)); // NOI18N
        GetStarted.setText("Get started by:");
        LandingPNLWhite.add(GetStarted, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));
        LandingPNLWhite.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));

        RegisterLanding.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        RegisterLanding.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RegisterLanding.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegisterLandingMouseClicked(evt);
            }
        });

        SignUpRegister1.setFont(new java.awt.Font("Palatino Linotype", 3, 18)); // NOI18N
        SignUpRegister1.setText("Register");

        javax.swing.GroupLayout RegisterLandingLayout = new javax.swing.GroupLayout(RegisterLanding);
        RegisterLanding.setLayout(RegisterLandingLayout);
        RegisterLandingLayout.setHorizontalGroup(
            RegisterLandingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegisterLandingLayout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(SignUpRegister1))
        );
        RegisterLandingLayout.setVerticalGroup(
            RegisterLandingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegisterLandingLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(SignUpRegister1))
        );

        LandingPNLWhite.add(RegisterLanding, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 70, 30));
        LandingPNLWhite.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 330, 10));
        LandingPNLWhite.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 320, 10));

        getContentPane().add(LandingPNLWhite, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 320, 440));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SignUpLandingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUpLandingMouseClicked
  
    }//GEN-LAST:event_SignUpLandingMouseClicked

    private void RegisterLandingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterLandingMouseClicked
        register register = new register();
        register.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RegisterLandingMouseClicked

    private void SignUpRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUpRegisterMouseClicked
        login login = new login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SignUpRegisterMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(landing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(landing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(landing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(landing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new landing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CatchDesc1;
    private javax.swing.JLabel CatchDesc2;
    private javax.swing.JLabel CatchDesc3;
    private javax.swing.JLabel CatchDesc4;
    private javax.swing.JLabel GetStarted;
    private javax.swing.JLabel IntroDesc;
    private javax.swing.JLabel IntroDesc2;
    private javax.swing.JLabel IntroDesc3;
    private javax.swing.JPanel LandingPNLBlack;
    private javax.swing.JPanel LandingPNLWhite;
    private javax.swing.JLabel ManwhalegendsLogo;
    private javax.swing.JPanel RegisterLanding;
    private javax.swing.JPanel SignUpLanding;
    private javax.swing.JLabel SignUpRegister;
    private javax.swing.JLabel SignUpRegister1;
    private javax.swing.JLabel Title1;
    private javax.swing.JLabel Title2;
    private javax.swing.JLabel Title3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    // End of variables declaration//GEN-END:variables
}
