/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userdashboard;

import javax.swing.JOptionPane;
import manwhalegends.login;
import users.managemanwha;
import users.manageuser;

/**
 *
 * @author Resty
 */
public class admindashboard extends javax.swing.JFrame {

    /**
     * Creates new form admindashboard
     */
    public admindashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        MenuPNL = new javax.swing.JPanel();
        OverviewAdmin = new javax.swing.JButton();
        Users = new javax.swing.JButton();
        ManageManwha = new javax.swing.JButton();
        LogoutAdmin = new javax.swing.JButton();
        SystemLogo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        SignUpHeader = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        SignUpHeader1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        SignUpHeader2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenuPNL.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        OverviewAdmin.setText("Overview");
        OverviewAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        OverviewAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OverviewAdminActionPerformed(evt);
            }
        });
        MenuPNL.add(OverviewAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        Users.setText("Users");
        Users.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Users.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsersActionPerformed(evt);
            }
        });
        MenuPNL.add(Users, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 70, -1));

        ManageManwha.setText("Manwha");
        ManageManwha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ManageManwha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageManwhaActionPerformed(evt);
            }
        });
        MenuPNL.add(ManageManwha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 81, -1));

        LogoutAdmin.setText("Logout");
        LogoutAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogoutAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutAdminActionPerformed(evt);
            }
        });
        MenuPNL.add(LogoutAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        jPanel1.add(MenuPNL, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 130, 340));

        SystemLogo.setBackground(new java.awt.Color(0, 0, 0));
        SystemLogo.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        SystemLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/images__2_-removebg-preview.png"))); // NOI18N
        SystemLogo.setMaximumSize(new java.awt.Dimension(60, 60));
        SystemLogo.setMinimumSize(new java.awt.Dimension(60, 60));
        jPanel1.add(SystemLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 70));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SignUpHeader.setFont(new java.awt.Font("Palatino Linotype", 3, 40)); // NOI18N
        SignUpHeader.setText("Welcome, Admin!");
        jPanel2.add(SignUpHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, -1, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 470, 20));

        SignUpHeader1.setFont(new java.awt.Font("Palatino Linotype", 2, 18)); // NOI18N
        SignUpHeader1.setText("Total Manwhas");
        jPanel2.add(SignUpHeader1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, 30));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 470, 20));

        SignUpHeader2.setFont(new java.awt.Font("Palatino Linotype", 3, 24)); // NOI18N
        SignUpHeader2.setText("Overview Dashboard");
        jPanel2.add(SignUpHeader2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menu_book_40dp_1F1F1F_FILL0_wght400_GRAD0_opsz40.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 40, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 470, 380));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 420));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void OverviewAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OverviewAdminActionPerformed
    
    }//GEN-LAST:event_OverviewAdminActionPerformed

    private void UsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsersActionPerformed
        manageuser manageuser = new manageuser();
        manageuser.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_UsersActionPerformed

    private void ManageManwhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageManwhaActionPerformed
     managemanwha managemanwha = new managemanwha();
     managemanwha.setVisible(true);
     this.dispose();
    }//GEN-LAST:event_ManageManwhaActionPerformed

    private void LogoutAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutAdminActionPerformed
        if (JOptionPane.showConfirmDialog(this,
        "Are you sure you want to logout?",
        "Confirm Logout",
        JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {

    new login().setVisible(true);
    this.dispose();
}
        
    }//GEN-LAST:event_LogoutAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admindashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admindashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admindashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admindashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admindashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogoutAdmin;
    private javax.swing.JButton ManageManwha;
    private javax.swing.JPanel MenuPNL;
    private javax.swing.JButton OverviewAdmin;
    private javax.swing.JLabel SignUpHeader;
    private javax.swing.JLabel SignUpHeader1;
    private javax.swing.JLabel SignUpHeader2;
    private javax.swing.JLabel SystemLogo;
    private javax.swing.JButton Users;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
