/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userdashboard;

import config.Session;
import config.config;
import javax.swing.JOptionPane;
import manwhalegends.login;
import users.favoritesreader;
import users.readerservice;

/**
 *
 * @author Resty
 */
public class readerdashboard extends javax.swing.JFrame {

    /**
     * Creates new form readerdashboard
     */
    //constructor ni wally boldyola
    public readerdashboard() {
        initComponents();
        loadReaderProfile();
    }
    
    //method para modisplay and users profile
public void loadReaderProfile() {

    int userId = Session.getInstance().getUserId();
    String type = Session.getInstance().getUserType();

    if (!type.equalsIgnoreCase("reader")) {
        javax.swing.JOptionPane.showMessageDialog(this, "Access Denied!");
        new login().setVisible(true);
        this.dispose();
        return;
    }

    try {
        config con = new config();
        java.sql.Connection cn = con.connectDB();
        java.sql.PreparedStatement pst = cn.prepareStatement(
            "SELECT u_id, name, email, type, status FROM tbl_Acc WHERE u_id = ?"
        );

        pst.setInt(1, userId);
        java.sql.ResultSet rs = pst.executeQuery();

        if (rs.next()) {
            Rid.setText(String.valueOf(rs.getInt("u_id")));
            Rusername.setText(rs.getString("name"));
            Remail.setText(rs.getString("email"));
            Rtype.setText(rs.getString("type"));
            Rstatus.setText(rs.getString("status"));
        }

        rs.close();
        pst.close();
        cn.close();

    } catch (Exception e) {
        e.printStackTrace();
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        MenuPNL = new javax.swing.JPanel();
        ProfileReader = new javax.swing.JButton();
        Explore = new javax.swing.JButton();
        Favorites = new javax.swing.JButton();
        LogoutAdmin = new javax.swing.JButton();
        SystemLogo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        SignUpHeader = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        SignUpHeader2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Rstatus = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Rid = new javax.swing.JLabel();
        Rusername = new javax.swing.JLabel();
        Remail = new javax.swing.JLabel();
        Rtype = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenuPNL.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ProfileReader.setText("Profile");
        ProfileReader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfileReaderActionPerformed(evt);
            }
        });
        MenuPNL.add(ProfileReader, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        Explore.setText("Explore");
        Explore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExploreActionPerformed(evt);
            }
        });
        MenuPNL.add(Explore, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 70, -1));

        Favorites.setText("Favorites");
        Favorites.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FavoritesActionPerformed(evt);
            }
        });
        MenuPNL.add(Favorites, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 81, -1));

        LogoutAdmin.setText("Logout");
        LogoutAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutAdminActionPerformed(evt);
            }
        });
        MenuPNL.add(LogoutAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 266, -1, -1));

        jPanel1.add(MenuPNL, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 130, 350));

        SystemLogo.setBackground(new java.awt.Color(0, 0, 0));
        SystemLogo.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        SystemLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/images__2_-removebg-preview.png"))); // NOI18N
        SystemLogo.setMaximumSize(new java.awt.Dimension(60, 60));
        SystemLogo.setMinimumSize(new java.awt.Dimension(60, 60));
        jPanel1.add(SystemLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 70));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SignUpHeader.setFont(new java.awt.Font("Palatino Linotype", 3, 40)); // NOI18N
        SignUpHeader.setText("Welcome, Reader!");
        jPanel2.add(SignUpHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 470, 20));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 470, 20));

        SignUpHeader2.setFont(new java.awt.Font("Palatino Linotype", 3, 24)); // NOI18N
        SignUpHeader2.setText("Profile");
        jPanel2.add(SignUpHeader2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/person_book_40dp_1F1F1F_FILL0_wght400_GRAD0_opsz40.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 40, 30));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Palatino Linotype", 2, 18)); // NOI18N
        jLabel1.setText("Status:");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        Rstatus.setFont(new java.awt.Font("Palatino Linotype", 2, 18)); // NOI18N
        jPanel3.add(Rstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 110, 30));

        jLabel4.setFont(new java.awt.Font("Palatino Linotype", 2, 18)); // NOI18N
        jLabel4.setText("Username:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel5.setFont(new java.awt.Font("Palatino Linotype", 2, 18)); // NOI18N
        jLabel5.setText("Type:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel6.setFont(new java.awt.Font("Palatino Linotype", 2, 18)); // NOI18N
        jLabel6.setText("Email:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel7.setFont(new java.awt.Font("Palatino Linotype", 2, 18)); // NOI18N
        jLabel7.setText("UserID:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        Rid.setFont(new java.awt.Font("Palatino Linotype", 2, 18)); // NOI18N
        jPanel3.add(Rid, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 90, 30));

        Rusername.setFont(new java.awt.Font("Palatino Linotype", 2, 18)); // NOI18N
        jPanel3.add(Rusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 190, 30));

        Remail.setFont(new java.awt.Font("Palatino Linotype", 2, 18)); // NOI18N
        jPanel3.add(Remail, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 240, 20));

        Rtype.setFont(new java.awt.Font("Palatino Linotype", 2, 18)); // NOI18N
        jPanel3.add(Rtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 170, 30));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 410, 230));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 470, 380));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProfileReaderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfileReaderActionPerformed
readerdashboard readerdashboard = new readerdashboard();
readerdashboard.setVisible(true);
this.dispose();
    }//GEN-LAST:event_ProfileReaderActionPerformed

    private void ExploreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExploreActionPerformed
readerservice readerservice = new readerservice();
readerservice.setVisible(true);
this.dispose();
    }//GEN-LAST:event_ExploreActionPerformed

    private void FavoritesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FavoritesActionPerformed
 favoritesreader favoritesreader = new favoritesreader();
 favoritesreader.setVisible(true);
 this.dispose();
    }//GEN-LAST:event_FavoritesActionPerformed

    private void LogoutAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutAdminActionPerformed
   if (JOptionPane.showConfirmDialog(this,
        "Are you sure you want to logout?",
        "Confirm Logout",
        JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {

    new login().setVisible(true);
    this.dispose();        
   }
    }//GEN-LAST:event_LogoutAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(readerdashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(readerdashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(readerdashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(readerdashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new readerdashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Explore;
    private javax.swing.JButton Favorites;
    private javax.swing.JButton LogoutAdmin;
    private javax.swing.JPanel MenuPNL;
    private javax.swing.JButton ProfileReader;
    private javax.swing.JLabel Remail;
    private javax.swing.JLabel Rid;
    private javax.swing.JLabel Rstatus;
    private javax.swing.JLabel Rtype;
    private javax.swing.JLabel Rusername;
    private javax.swing.JLabel SignUpHeader;
    private javax.swing.JLabel SignUpHeader2;
    private javax.swing.JLabel SystemLogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
