    /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CRUDReader;

import config.Session;
import config.config;
import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Resty
 */
public class editprofile extends javax.swing.JFrame {

    private String selectedImagePath = "";
    /**
     * Creates new form editprofile
     */
    public editprofile() {
        initComponents();
        loadUserData();
        
        getRootPane().setDefaultButton(Save);
    }
    private void loadUserData() {

    try {
        Connection conn = config.connectDB();
        String sql = "SELECT name, email, password, image FROM tbl_Acc WHERE u_id=?";
        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setInt(1, Session.getInstance().getUserId());

        ResultSet rs = pst.executeQuery();

        if (rs.next()) {

            EdName.setText(rs.getString("name"));
            EdEmail.setText(rs.getString("email"));
            EdPass.setText(rs.getString("password"));

            selectedImagePath = rs.getString("image");

            if (selectedImagePath != null && !selectedImagePath.isEmpty()) {
                ImageIcon icon = new ImageIcon(selectedImagePath);
                Image img = icon.getImage().getScaledInstance(165, 175, Image.SCALE_SMOOTH);
                ImagePreview.setIcon(new ImageIcon(img));
            }
        }

        conn.close();

    } catch (Exception e) {
        e.printStackTrace();
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        AddHeader = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        AStatus = new javax.swing.JLabel();
        ATitle = new javax.swing.JLabel();
        AGenre = new javax.swing.JLabel();
        AAuthor = new javax.swing.JLabel();
        Cancelbtn = new javax.swing.JButton();
        Addbtn = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        AddStatus = new javax.swing.JTextField();
        AddTitle = new javax.swing.JTextField();
        AddGenre = new javax.swing.JTextField();
        AddAuthor = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        AddHeader1 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        EName = new javax.swing.JLabel();
        EEmail = new javax.swing.JLabel();
        EPAssword = new javax.swing.JLabel();
        Cancelbtn1 = new javax.swing.JButton();
        Save = new javax.swing.JButton();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        EdName = new javax.swing.JTextField();
        EdEmail = new javax.swing.JTextField();
        EdPass = new javax.swing.JTextField();
        ImagePreview = new javax.swing.JLabel();
        ChooseImage = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/manwhalegends.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 240, 220, 100));

        AddHeader.setFont(new java.awt.Font("Palatino Linotype", 3, 36)); // NOI18N
        AddHeader.setText("Add Manwha");
        jPanel2.add(AddHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, -1, 40));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 560, 10));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 560, 10));

        AStatus.setFont(new java.awt.Font("Palatino Linotype", 2, 18)); // NOI18N
        AStatus.setText("Status:");
        jPanel2.add(AStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        ATitle.setFont(new java.awt.Font("Palatino Linotype", 2, 18)); // NOI18N
        ATitle.setText("Title:");
        jPanel2.add(ATitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        AGenre.setFont(new java.awt.Font("Palatino Linotype", 2, 18)); // NOI18N
        AGenre.setText("Genre:");
        jPanel2.add(AGenre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        AAuthor.setFont(new java.awt.Font("Palatino Linotype", 2, 18)); // NOI18N
        AAuthor.setText("Author:");
        jPanel2.add(AAuthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        Cancelbtn.setText("Cancel");
        Cancelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelbtnActionPerformed(evt);
            }
        });
        jPanel2.add(Cancelbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 70, 40));

        Addbtn.setText("Add");
        Addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddbtnActionPerformed(evt);
            }
        });
        jPanel2.add(Addbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 70, 40));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 50, 10));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 50, 10));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 40, 10));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 60, 10));

        AddStatus.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        AddStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddStatusActionPerformed(evt);
            }
        });
        jPanel2.add(AddStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 360, 30));

        AddTitle.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        AddTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddTitleActionPerformed(evt);
            }
        });
        jPanel2.add(AddTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 360, 30));

        AddGenre.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        AddGenre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddGenreActionPerformed(evt);
            }
        });
        jPanel2.add(AddGenre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 360, 30));

        AddAuthor.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        AddAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddAuthorActionPerformed(evt);
            }
        });
        jPanel2.add(AddAuthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 360, 30));

        jFrame1.getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 380));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AddHeader1.setFont(new java.awt.Font("Palatino Linotype", 3, 24)); // NOI18N
        AddHeader1.setText("Edit Profile");
        jPanel1.add(AddHeader1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, -1, 40));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 620, 10));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 610, 10));

        EName.setFont(new java.awt.Font("Palatino Linotype", 2, 18)); // NOI18N
        EName.setText("Name:");
        jPanel1.add(EName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        EEmail.setFont(new java.awt.Font("Palatino Linotype", 2, 18)); // NOI18N
        EEmail.setText("Email:");
        jPanel1.add(EEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        EPAssword.setFont(new java.awt.Font("Palatino Linotype", 2, 18)); // NOI18N
        EPAssword.setText("Password:");
        jPanel1.add(EPAssword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        Cancelbtn1.setText("Cancel");
        Cancelbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancelbtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(Cancelbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, 70, 30));

        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        jPanel1.add(Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 400, 70, 30));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 50, 20));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 50, 20));
        jPanel1.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 70, 20));

        EdName.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        EdName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdNameActionPerformed(evt);
            }
        });
        jPanel1.add(EdName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 360, 30));

        EdEmail.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        EdEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdEmailActionPerformed(evt);
            }
        });
        jPanel1.add(EdEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 360, 30));

        EdPass.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        EdPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdPassActionPerformed(evt);
            }
        });
        jPanel1.add(EdPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 360, 30));
        jPanel1.add(ImagePreview, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 180, 170));

        ChooseImage.setText("Choose Image");
        ChooseImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChooseImageActionPerformed(evt);
            }
        });
        jPanel1.add(ChooseImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/manwhalegends.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 40, 220, 100));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 440));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CancelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelbtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_CancelbtnActionPerformed

    private void AddbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddbtnActionPerformed
        
    }//GEN-LAST:event_AddbtnActionPerformed

    private void AddStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddStatusActionPerformed

    private void AddTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddTitleActionPerformed

    private void AddGenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddGenreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddGenreActionPerformed

    private void AddAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddAuthorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddAuthorActionPerformed

    private void Cancelbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancelbtn1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_Cancelbtn1ActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
       try {

    Connection conn = config.connectDB();

    String sql = "UPDATE tbl_Acc SET name=?, email=?, password=?, image=? WHERE u_id=?";

    PreparedStatement pst = conn.prepareStatement(sql);

    pst.setString(1, EdName.getText());
    pst.setString(2, EdEmail.getText());
    pst.setString(3, EdPass.getText());
    pst.setString(4, selectedImagePath);
    pst.setInt(5, Session.getInstance().getUserId());

    pst.executeUpdate();

    JOptionPane.showMessageDialog(this, "Profile Updated!");

    conn.close();
    this.dispose();

} catch (Exception e) {
    System.out.println(e);
}
    }//GEN-LAST:event_SaveActionPerformed

    private void EdNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdNameActionPerformed

    private void EdEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdEmailActionPerformed

    private void EdPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdPassActionPerformed

    private void ChooseImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChooseImageActionPerformed
       JFileChooser chooser = new JFileChooser();
chooser.showOpenDialog(null);

File file = chooser.getSelectedFile();

if (file != null) {

    selectedImagePath = file.getAbsolutePath();

    ImageIcon icon = new ImageIcon(selectedImagePath);
    Image img = icon.getImage().getScaledInstance(120, 120, Image.SCALE_SMOOTH);
    ImagePreview.setIcon(new ImageIcon(img));
}
    }//GEN-LAST:event_ChooseImageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editprofile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AAuthor;
    private javax.swing.JLabel AGenre;
    private javax.swing.JLabel AStatus;
    private javax.swing.JLabel ATitle;
    private javax.swing.JTextField AddAuthor;
    private javax.swing.JTextField AddGenre;
    private javax.swing.JLabel AddHeader;
    private javax.swing.JLabel AddHeader1;
    private javax.swing.JTextField AddStatus;
    private javax.swing.JTextField AddTitle;
    private javax.swing.JButton Addbtn;
    private javax.swing.JButton Cancelbtn;
    private javax.swing.JButton Cancelbtn1;
    private javax.swing.JButton ChooseImage;
    private javax.swing.JLabel EEmail;
    private javax.swing.JLabel EName;
    private javax.swing.JLabel EPAssword;
    private javax.swing.JTextField EdEmail;
    private javax.swing.JTextField EdName;
    private javax.swing.JTextField EdPass;
    private javax.swing.JLabel ImagePreview;
    private javax.swing.JButton Save;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    // End of variables declaration//GEN-END:variables
}
