/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package users;

import config.Session;
import config.config;
import javax.swing.JOptionPane;
import manwhalegends.login;
import userdashboard.readerdashboard;

/**
 *
 * @author Resty
 */
public class favoritesreader extends javax.swing.JFrame {

    /**
     * Creates new form favoritesreader
     */
    public favoritesreader() {
        initComponents();
        loadFavorites();
    }
    
    private void loadFavorites() {
    config cfg = new config();
    int userId = Session.getInstance().getUserId();
    cfg.getUserFavorites(userId, favoritesTable);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ReaderMenu = new javax.swing.JPanel();
        ReaderProfile = new javax.swing.JButton();
        Explore = new javax.swing.JButton();
        Favorites = new javax.swing.JButton();
        LogoutReader = new javax.swing.JButton();
        SystemLogo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        FavoritesHeader = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        favoritesTable = new javax.swing.JTable();
        Favoritesbtn = new javax.swing.JButton();
        Backbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ReaderMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ReaderProfile.setText("Profile");
        ReaderProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReaderProfileActionPerformed(evt);
            }
        });
        ReaderMenu.add(ReaderProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        Explore.setText("Explore");
        Explore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExploreActionPerformed(evt);
            }
        });
        ReaderMenu.add(Explore, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 70, -1));

        Favorites.setText("Favorites");
        Favorites.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FavoritesActionPerformed(evt);
            }
        });
        ReaderMenu.add(Favorites, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 81, -1));

        LogoutReader.setText("Logout");
        LogoutReader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutReaderActionPerformed(evt);
            }
        });
        ReaderMenu.add(LogoutReader, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 266, -1, -1));

        jPanel1.add(ReaderMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 130, 340));

        SystemLogo.setBackground(new java.awt.Color(0, 0, 0));
        SystemLogo.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        SystemLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/images__2_-removebg-preview.png"))); // NOI18N
        SystemLogo.setMaximumSize(new java.awt.Dimension(60, 60));
        SystemLogo.setMinimumSize(new java.awt.Dimension(60, 60));
        jPanel1.add(SystemLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 90, 60));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FavoritesHeader.setFont(new java.awt.Font("Palatino Linotype", 3, 36)); // NOI18N
        FavoritesHeader.setText("Favorites");
        jPanel2.add(FavoritesHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, -1, -1));

        jSeparator1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 500, 0));

        favoritesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(favoritesTable);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 500, 300));

        Favoritesbtn.setText("Remove from favorites");
        Favoritesbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FavoritesbtnActionPerformed(evt);
            }
        });
        jPanel2.add(Favoritesbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        Backbtn.setText("Refresh");
        Backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbtnActionPerformed(evt);
            }
        });
        jPanel2.add(Backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 500, 380));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReaderProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReaderProfileActionPerformed
        readerdashboard readerdashboard = new readerdashboard();
        readerdashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ReaderProfileActionPerformed

    private void ExploreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExploreActionPerformed
    readerservice readerservice = new readerservice();
    readerservice.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_ExploreActionPerformed

    private void FavoritesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FavoritesActionPerformed

    }//GEN-LAST:event_FavoritesActionPerformed

    private void LogoutReaderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutReaderActionPerformed
        if (JOptionPane.showConfirmDialog(this,
            "Are you sure you want to logout?",
            "Confirm Logout",
            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {

        new login().setVisible(true);
        this.dispose();
        }
    }//GEN-LAST:event_LogoutReaderActionPerformed

    private void BackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbtnActionPerformed
     loadFavorites();
    }//GEN-LAST:event_BackbtnActionPerformed

    private void FavoritesbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FavoritesbtnActionPerformed
     
    int selectedRow = favoritesTable.getSelectedRow();

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Select a manwha first!");
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(
            this,
            "Remove from favorites?",
            "Confirm",
            JOptionPane.YES_NO_OPTION
    );

    if (confirm == JOptionPane.YES_OPTION) {

        int manwhaId = Integer.parseInt(
                favoritesTable.getValueAt(selectedRow, 0).toString()
        );

        int userId = Session.getInstance().getUserId();

        config cfg = new config();
        cfg.removeFromFavorites(userId, manwhaId);

        JOptionPane.showMessageDialog(this, "Removed Successfully!");
        loadFavorites(); // refresh table
    }

    }//GEN-LAST:event_FavoritesbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(favoritesreader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(favoritesreader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(favoritesreader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(favoritesreader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new favoritesreader().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Backbtn;
    private javax.swing.JButton Explore;
    private javax.swing.JButton Favorites;
    private javax.swing.JLabel FavoritesHeader;
    private javax.swing.JButton Favoritesbtn;
    private javax.swing.JButton LogoutReader;
    private javax.swing.JPanel ReaderMenu;
    private javax.swing.JButton ReaderProfile;
    private javax.swing.JLabel SystemLogo;
    private javax.swing.JTable favoritesTable;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
