/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package users;

import CRUDadmin.Add;
import CRUDadmin.Update;
import config.config;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import manwhalegends.login;
import userdashboard.admindashboard;



/**
 *
 * @author Resty
 */
public class managemanwha extends javax.swing.JFrame {
config cfg = new config();
    /**
     * Creates new form managemanwha
     */
    public managemanwha() {
        initComponents();
        loadManwha();
        adminManwhaTable.setShowGrid(false);
        adminManwhaTable.setRowHeight(25);
    }
 

    public void loadManwha() {
    try {
        Connection con = DriverManager.getConnection("jdbc:sqlite:AlGUI.db");
        String sql = "SELECT * FROM tbl_manwha";
        PreparedStatement pst = con.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();

        DefaultTableModel model = (DefaultTableModel) adminManwhaTable.getModel();
        model.setRowCount(0); // clear table

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("m_id"),
                rs.getString("title"),
                rs.getString("genre"),
                rs.getString("author"),
                rs.getString("status")
            });
        }

        con.close();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Load Error: " + e.getMessage());
    }
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        MenuPNL = new javax.swing.JPanel();
        OverviewAdmin = new javax.swing.JButton();
        Users = new javax.swing.JButton();
        ManageManwha = new javax.swing.JButton();
        LogoutAdmin = new javax.swing.JButton();
        SystemLogo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        SignUpHeader = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        refrsh = new javax.swing.JButton();
        Add = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        adminManwhaTable = new javax.swing.JTable();
        btnSearch = new javax.swing.JButton();
        Searchb = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenuPNL.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        OverviewAdmin.setText("Overview");
        OverviewAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        OverviewAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OverviewAdminActionPerformed(evt);
            }
        });
        MenuPNL.add(OverviewAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        Users.setText("Users");
        Users.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Users.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsersActionPerformed(evt);
            }
        });
        MenuPNL.add(Users, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 70, -1));

        ManageManwha.setText("Manwha");
        ManageManwha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ManageManwha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageManwhaActionPerformed(evt);
            }
        });
        MenuPNL.add(ManageManwha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 81, -1));

        LogoutAdmin.setText("Logout");
        LogoutAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogoutAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutAdminActionPerformed(evt);
            }
        });
        MenuPNL.add(LogoutAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        jPanel1.add(MenuPNL, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 110, 340));

        SystemLogo.setBackground(new java.awt.Color(0, 0, 0));
        SystemLogo.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        SystemLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/images__2_-removebg-preview.png"))); // NOI18N
        SystemLogo.setMaximumSize(new java.awt.Dimension(60, 60));
        SystemLogo.setMinimumSize(new java.awt.Dimension(60, 60));
        jPanel1.add(SystemLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 70));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SignUpHeader.setFont(new java.awt.Font("Palatino Linotype", 3, 40)); // NOI18N
        SignUpHeader.setText("Manage Manwhas");
        jPanel2.add(SignUpHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, -1, 40));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 510, 10));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 490, 10));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menu_book_40dp_1F1F1F_FILL0_wght400_GRAD0_opsz40.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 40, 30));

        refrsh.setText("Refresh");
        refrsh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refrshActionPerformed(evt);
            }
        });
        jPanel2.add(refrsh, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, -1));

        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        jPanel2.add(Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        jPanel2.add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        jPanel2.add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));

        adminManwhaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Title", "Genre", "Author", "Status"
            }
        ));
        jScrollPane1.setViewportView(adminManwhaTable);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 510, 290));

        btnSearch.setBackground(new java.awt.Color(255, 255, 255));
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search.png"))); // NOI18N
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel2.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 30, 30));

        Searchb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchbActionPerformed(evt);
            }
        });
        jPanel2.add(Searchb, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 110, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 510, 380));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OverviewAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OverviewAdminActionPerformed
admindashboard admindashboard = new admindashboard();
admindashboard.setVisible(true);
this.dispose();
    }//GEN-LAST:event_OverviewAdminActionPerformed

    private void UsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsersActionPerformed
        manageuser manageuser = new manageuser();
        manageuser.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_UsersActionPerformed

    private void ManageManwhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageManwhaActionPerformed

    }//GEN-LAST:event_ManageManwhaActionPerformed

    private void LogoutAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutAdminActionPerformed
        if (JOptionPane.showConfirmDialog(this,
            "Are you sure you want to logout?",
            "Confirm Logout",
            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {

        new login().setVisible(true);
        this.dispose();
        }

    }//GEN-LAST:event_LogoutAdminActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        int row = adminManwhaTable.getSelectedRow();

if(row == -1){
    JOptionPane.showMessageDialog(this, "Select a row first!");
    return;
}

int id = Integer.parseInt(adminManwhaTable.getValueAt(row, 0).toString());
String title = adminManwhaTable.getValueAt(row, 1).toString();
String genre = adminManwhaTable.getValueAt(row, 2).toString();
String author = adminManwhaTable.getValueAt(row, 3).toString();
String status = adminManwhaTable.getValueAt(row, 4).toString();

new Update(id, title, genre, author, status).setVisible(true);
    }//GEN-LAST:event_UpdateActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
            String keyword = Searchb.getText().trim();
    config cfg = new config();

    if (!keyword.isEmpty()) {
        cfg.searchAdminManwha(keyword, adminManwhaTable);
    } else {
        loadManwha();
    }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void SearchbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchbActionPerformed
         String keyword = Searchb.getText().trim();
    config cfg = new config();

    if (!keyword.isEmpty()) {
        cfg.searchManwha(keyword, adminManwhaTable);
    } else {
        loadManwha();
    }
    }//GEN-LAST:event_SearchbActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
       int row = adminManwhaTable.getSelectedRow();

if(row == -1){
    JOptionPane.showMessageDialog(this, "Select a row first!");
    return;
}

int confirm = JOptionPane.showConfirmDialog(this, 
        "Are you sure you want to delete this manwha?",
        "Confirm Delete",
        JOptionPane.YES_NO_OPTION);

if(confirm == JOptionPane.YES_OPTION){
    int id = Integer.parseInt(adminManwhaTable.getValueAt(row, 0).toString());
    cfg.deleteManwha(id);
    loadManwha();
}
    }//GEN-LAST:event_DeleteActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed

Add Add = new Add();
Add.setVisible(true);

    }//GEN-LAST:event_AddActionPerformed

    private void refrshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refrshActionPerformed
        loadManwha();
    }//GEN-LAST:event_refrshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(managemanwha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(managemanwha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(managemanwha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(managemanwha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new managemanwha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton AddtoF;
    private javax.swing.JButton AddtoF1;
    private javax.swing.JButton Delete;
    private javax.swing.JButton LogoutAdmin;
    private javax.swing.JButton ManageManwha;
    private javax.swing.JPanel MenuPNL;
    private javax.swing.JButton OverviewAdmin;
    private javax.swing.JTextField Searchb;
    private javax.swing.JLabel SignUpHeader;
    private javax.swing.JLabel SystemLogo;
    private javax.swing.JButton Update;
    private javax.swing.JButton Users;
    private javax.swing.JTable adminManwhaTable;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton refrsh;
    // End of variables declaration//GEN-END:variables
}
