/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package users;

import config.config;
import javax.swing.JOptionPane;
import manwhalegends.login;
import userdashboard.admindashboard;

/**
 *
 * @author Resty
 */
public class manageuser extends javax.swing.JFrame {

    /**
     * Creates new form manageuser
     */
    public manageuser() {
        initComponents();
        loadUsers();
    }

    public void loadUsers() {
    config con = new config();
    con.getAllUsers(UsersTable);
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BodyPanel = new javax.swing.JPanel();
        MenuPNL = new javax.swing.JPanel();
        OverviewAdmin = new javax.swing.JButton();
        Users = new javax.swing.JButton();
        Manwha = new javax.swing.JButton();
        LogoutAdmin = new javax.swing.JButton();
        SystemLogo = new javax.swing.JLabel();
        MainPNL = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        ManageUserHeader = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        UsersTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BodyPanel.setBackground(new java.awt.Color(0, 0, 0));
        BodyPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenuPNL.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        OverviewAdmin.setText("Overview");
        OverviewAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OverviewAdminActionPerformed(evt);
            }
        });
        MenuPNL.add(OverviewAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        Users.setText("Users");
        Users.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsersActionPerformed(evt);
            }
        });
        MenuPNL.add(Users, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 70, -1));

        Manwha.setText("Manwha");
        Manwha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManwhaActionPerformed(evt);
            }
        });
        MenuPNL.add(Manwha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 81, -1));

        LogoutAdmin.setText("Logout");
        LogoutAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutAdminActionPerformed(evt);
            }
        });
        MenuPNL.add(LogoutAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        BodyPanel.add(MenuPNL, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 120, 330));

        SystemLogo.setBackground(new java.awt.Color(0, 0, 0));
        SystemLogo.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        SystemLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/images__2_-removebg-preview.png"))); // NOI18N
        SystemLogo.setMaximumSize(new java.awt.Dimension(60, 60));
        SystemLogo.setMinimumSize(new java.awt.Dimension(60, 60));
        BodyPanel.add(SystemLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 70));

        MainPNL.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        MainPNL.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 470, 20));

        ManageUserHeader.setFont(new java.awt.Font("Palatino Linotype", 3, 24)); // NOI18N
        ManageUserHeader.setText("Manage Users");
        MainPNL.add(ManageUserHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        UsersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(UsersTable);

        MainPNL.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 460, 320));

        BodyPanel.add(MainPNL, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 460, 370));

        getContentPane().add(BodyPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OverviewAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OverviewAdminActionPerformed
    admindashboard admindashboard = new admindashboard();
    admindashboard.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_OverviewAdminActionPerformed

    private void UsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsersActionPerformed

    }//GEN-LAST:event_UsersActionPerformed

    private void ManwhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManwhaActionPerformed
managemanwha managemanwha = new managemanwha();
managemanwha.setVisible(true);
this.dispose();
    }//GEN-LAST:event_ManwhaActionPerformed

    private void LogoutAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutAdminActionPerformed
           if (JOptionPane.showConfirmDialog(this,
        "Are you sure you want to logout?",
        "Confirm Logout",
        JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {

    new login().setVisible(true);
    this.dispose();
           }
    }//GEN-LAST:event_LogoutAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manageuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manageuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manageuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manageuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manageuser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BodyPanel;
    private javax.swing.JButton LogoutAdmin;
    private javax.swing.JPanel MainPNL;
    private javax.swing.JLabel ManageUserHeader;
    private javax.swing.JButton Manwha;
    private javax.swing.JPanel MenuPNL;
    private javax.swing.JButton OverviewAdmin;
    private javax.swing.JLabel SystemLogo;
    private javax.swing.JButton Users;
    private javax.swing.JTable UsersTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
