/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package users;

import config.Session;
import config.config;
import javax.swing.JOptionPane;
import manwhalegends.login;
import userdashboard.readerdashboard;


/**
 *
 * @author Resty
 */
public class readerservice extends javax.swing.JFrame {

    /**
     * Creates new form readerservice
     */
public readerservice() {
             initComponents();
             loadManwha();
          
             getRootPane().setDefaultButton(LogoutReader);
    }
    
private void loadManwha() {
             config cfg= new config();
             cfg.getAllManwha(manwhaTable);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        backgroundpanel = new javax.swing.JPanel();
        mainpnl = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        ReaderServiceHeader = new javax.swing.JLabel();
        ManwhaListTable = new javax.swing.JScrollPane();
        manwhaTable = new javax.swing.JTable();
        AddtoF = new javax.swing.JButton();
        Searchbar = new javax.swing.JTextField();
        Searchbtn = new javax.swing.JButton();
        MenuPnl = new javax.swing.JPanel();
        Explore = new javax.swing.JButton();
        ReaderProfile = new javax.swing.JButton();
        Favorites = new javax.swing.JButton();
        LogoutReader = new javax.swing.JButton();

        jScrollPane1.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backgroundpanel.setBackground(new java.awt.Color(0, 0, 0));
        backgroundpanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backgroundpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainpnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        mainpnl.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 630, 10));

        ReaderServiceHeader.setFont(new java.awt.Font("Palatino Linotype", 3, 24)); // NOI18N
        ReaderServiceHeader.setText("Discover Manwhas");
        mainpnl.add(ReaderServiceHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, -1, -1));

        manwhaTable.setBackground(new java.awt.Color(0, 0, 0));
        manwhaTable.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        manwhaTable.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        manwhaTable.setForeground(new java.awt.Color(255, 255, 255));
        manwhaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title ", "Genre", "Author", "Status"
            }
        ));
        ManwhaListTable.setViewportView(manwhaTable);

        mainpnl.add(ManwhaListTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 630, 320));

        AddtoF.setText("Add to Favorites");
        AddtoF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddtoFActionPerformed(evt);
            }
        });
        mainpnl.add(AddtoF, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 120, 30));

        Searchbar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchbarActionPerformed(evt);
            }
        });
        mainpnl.add(Searchbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 120, 30));

        Searchbtn.setBackground(new java.awt.Color(255, 255, 255));
        Searchbtn.setForeground(new java.awt.Color(255, 255, 255));
        Searchbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search.png"))); // NOI18N
        Searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchbtnActionPerformed(evt);
            }
        });
        mainpnl.add(Searchbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, 20, 30));

        backgroundpanel.add(mainpnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 630, 400));

        MenuPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Explore.setText("Explore");
        Explore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExploreActionPerformed(evt);
            }
        });
        MenuPnl.add(Explore, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 90, 40));

        ReaderProfile.setText("Profile");
        ReaderProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReaderProfileActionPerformed(evt);
            }
        });
        MenuPnl.add(ReaderProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 40));

        Favorites.setText("Favorites");
        Favorites.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FavoritesActionPerformed(evt);
            }
        });
        MenuPnl.add(Favorites, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 90, 40));

        LogoutReader.setText("Logout");
        LogoutReader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutReaderActionPerformed(evt);
            }
        });
        MenuPnl.add(LogoutReader, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 80, 40));

        backgroundpanel.add(MenuPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 630, 60));

        getContentPane().add(backgroundpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ReaderProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReaderProfileActionPerformed
        readerdashboard readerdashboard = new readerdashboard();
        readerdashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ReaderProfileActionPerformed

    private void ExploreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExploreActionPerformed

    }//GEN-LAST:event_ExploreActionPerformed

    private void FavoritesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FavoritesActionPerformed
        favoritesreader favoritesreader = new favoritesreader();
        favoritesreader.setVisible(true);
this.dispose();
    }//GEN-LAST:event_FavoritesActionPerformed

    private void LogoutReaderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutReaderActionPerformed
        if (JOptionPane.showConfirmDialog(this,
            "Are you sure you want to logout?",
            "Confirm Logout",
            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
 
 new login().setVisible(true);
 this.dispose();
                                                                                                                             }
    }//GEN-LAST:event_LogoutReaderActionPerformed

    private void AddtoFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddtoFActionPerformed
               int selectedRow = manwhaTable.getSelectedRow();

 if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Select a manwha first!");
        return;
                                                                                                                              }

int manwhaId = Integer.parseInt(manwhaTable.getValueAt(selectedRow, 0).toString());
int userId = Session.getInstance().getUserId();

       config cfg = new config();
       cfg.addToFavorites(userId, manwhaId);

    JOptionPane.showMessageDialog(this, "Added to Favorites!");
    

    }//GEN-LAST:event_AddtoFActionPerformed

    private void SearchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchbtnActionPerformed
         String keyword = Searchbtn.getText().trim();
         config cfg = new config();

 if (!keyword.isEmpty()) {
        cfg.searchManwha(keyword, manwhaTable);
    } else {
         loadManwha();
                                                                                                                                             }
    }//GEN-LAST:event_SearchbtnActionPerformed

    private void SearchbarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchbarActionPerformed
           String keyword = Searchbar.getText().trim();
           config cfg = new config();

    if (!keyword.isEmpty()) {
          cfg.searchManwha(keyword, manwhaTable);
    } else {
          loadManwha();
                                                                                                                                              }
    }//GEN-LAST:event_SearchbarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(readerservice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(readerservice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(readerservice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(readerservice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new readerservice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddtoF;
    private javax.swing.JButton Explore;
    private javax.swing.JButton Favorites;
    private javax.swing.JButton LogoutReader;
    private javax.swing.JScrollPane ManwhaListTable;
    private javax.swing.JPanel MenuPnl;
    private javax.swing.JButton ReaderProfile;
    private javax.swing.JLabel ReaderServiceHeader;
    private javax.swing.JTextField Searchbar;
    private javax.swing.JButton Searchbtn;
    private javax.swing.JPanel backgroundpanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JPanel mainpnl;
    private javax.swing.JTable manwhaTable;
    // End of variables declaration//GEN-END:variables
}
