/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CRUDadmin;

import config.config;
import javax.swing.JOptionPane;

/**
 *
 * @author Resty
 */
public class Add extends javax.swing.JFrame {
config cfg = new config();
    /**
     * Creates new form Add
     */
    public Add() {
        initComponents();
        getRootPane().setDefaultButton(Addbtn);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        AddHeader = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        AStatus = new javax.swing.JLabel();
        ATitle = new javax.swing.JLabel();
        AGenre = new javax.swing.JLabel();
        AAuthor = new javax.swing.JLabel();
        Cancelbtn = new javax.swing.JButton();
        Addbtn = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        AddStatus = new javax.swing.JTextField();
        AddTitle = new javax.swing.JTextField();
        AddGenre = new javax.swing.JTextField();
        AddAuthor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/manwhalegends.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 240, 220, 100));

        AddHeader.setFont(new java.awt.Font("Palatino Linotype", 3, 36)); // NOI18N
        AddHeader.setText("Add Manwha");
        jPanel1.add(AddHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, -1, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 560, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 560, 10));

        AStatus.setFont(new java.awt.Font("Palatino Linotype", 2, 18)); // NOI18N
        AStatus.setText("Status:");
        jPanel1.add(AStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        ATitle.setFont(new java.awt.Font("Palatino Linotype", 2, 18)); // NOI18N
        ATitle.setText("Title:");
        jPanel1.add(ATitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        AGenre.setFont(new java.awt.Font("Palatino Linotype", 2, 18)); // NOI18N
        AGenre.setText("Genre:");
        jPanel1.add(AGenre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        AAuthor.setFont(new java.awt.Font("Palatino Linotype", 2, 18)); // NOI18N
        AAuthor.setText("Author:");
        jPanel1.add(AAuthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        Cancelbtn.setText("Cancel");
        Cancelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelbtnActionPerformed(evt);
            }
        });
        jPanel1.add(Cancelbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 70, 40));

        Addbtn.setText("Add");
        Addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddbtnActionPerformed(evt);
            }
        });
        jPanel1.add(Addbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 70, 40));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 50, 10));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 50, 10));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 40, 10));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 60, 10));

        AddStatus.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        AddStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddStatusActionPerformed(evt);
            }
        });
        jPanel1.add(AddStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 360, 30));

        AddTitle.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        AddTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddTitleActionPerformed(evt);
            }
        });
        jPanel1.add(AddTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 360, 30));

        AddGenre.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        AddGenre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddGenreActionPerformed(evt);
            }
        });
        jPanel1.add(AddGenre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 360, 30));

        AddAuthor.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        AddAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddAuthorActionPerformed(evt);
            }
        });
        jPanel1.add(AddAuthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 360, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 380));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AddStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddStatusActionPerformed

    private void AddTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddTitleActionPerformed

    private void AddGenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddGenreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddGenreActionPerformed

    private void AddAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddAuthorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddAuthorActionPerformed

    private void AddbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddbtnActionPerformed
String title = AddTitle.getText();
String genre = AddGenre.getText();
String author = AddAuthor.getText();
String status = AddStatus.getText();

if(title.isEmpty() || genre.isEmpty() || author.isEmpty() || status.isEmpty()){
    JOptionPane.showMessageDialog(this, "All fields are required!");
    return;
}

cfg.addManwha(title, genre, author, status);

JOptionPane.showMessageDialog(this, "Manwha Added Successfully!");

// clear fields
AddTitle.setText("");
AddGenre.setText("");
AddAuthor.setText("");
AddStatus.setText("");

this.dispose();
    }//GEN-LAST:event_AddbtnActionPerformed

    private void CancelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelbtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_CancelbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AAuthor;
    private javax.swing.JLabel AGenre;
    private javax.swing.JLabel AStatus;
    private javax.swing.JLabel ATitle;
    private javax.swing.JTextField AddAuthor;
    private javax.swing.JTextField AddGenre;
    private javax.swing.JLabel AddHeader;
    private javax.swing.JTextField AddStatus;
    private javax.swing.JTextField AddTitle;
    private javax.swing.JButton Addbtn;
    private javax.swing.JButton Cancelbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    // End of variables declaration//GEN-END:variables
}
