/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CRUDadmin;

import config.config;
import javax.swing.JOptionPane;
import manwhalegends.login;

/**
 *
 * @author Resty
 */
public class ManageChapters extends javax.swing.JFrame {

    
    private int manwhaId;
private String manwhaTitle;

   public ManageChapters(int manwhaId, String manwhaTitle) {
    this.manwhaId = manwhaId;
    this.manwhaTitle = manwhaTitle;
    initComponents();
    ManageChapterTitle.setText(manwhaTitle);
    loadChapters();
}
   
   private void loadChapters() {
    try (java.sql.Connection conn = config.connectDB();
         java.sql.PreparedStatement pst = conn.prepareStatement(
             "SELECT chapter_no, chapter_title, last_free FROM tbl_chapters WHERE m_id=? ORDER BY CAST(chapter_no AS INTEGER)")) {

        pst.setInt(1, manwhaId);
        java.sql.ResultSet rs = pst.executeQuery();

        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(
            new String[]{"Chapter No", "Title", "Last Free"}, 0
        );

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("chapter_no"),
                rs.getString("chapter_title"),
                rs.getInt("last_free") == 1 ? "Yes" : "No"
            });
        }

        ManageChaptersTable.setModel(model);
        ManageChaptersTable.setDefaultEditor(Object.class, null);

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        MenuPNL = new javax.swing.JPanel();
        OverviewAdmin = new javax.swing.JButton();
        Users = new javax.swing.JButton();
        ManageManwha = new javax.swing.JButton();
        LogoutAdmin = new javax.swing.JButton();
        SystemLogo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        SignUpHeader = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        adminManwhaTable = new javax.swing.JTable();
        jSeparator3 = new javax.swing.JSeparator();
        Searchb = new javax.swing.JTextField();
        refrsh = new javax.swing.JButton();
        ManageChapters = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Add = new javax.swing.JButton();
        btnSearch1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        SystemLogo1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        ManageChaptersTable = new javax.swing.JTable();
        Deletech = new javax.swing.JButton();
        managepage = new javax.swing.JButton();
        Addch1 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        SearchBar = new javax.swing.JTextField();
        refrsh1 = new javax.swing.JButton();
        ManageChapterTitle = new javax.swing.JLabel();
        Closebut = new javax.swing.JButton();
        ManageChaptesrHeader = new javax.swing.JLabel();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenuPNL.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        OverviewAdmin.setText("Overview");
        OverviewAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        OverviewAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OverviewAdminActionPerformed(evt);
            }
        });
        MenuPNL.add(OverviewAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 40));

        Users.setText("Users");
        Users.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Users.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsersActionPerformed(evt);
            }
        });
        MenuPNL.add(Users, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 90, 40));

        ManageManwha.setText("Manwha");
        ManageManwha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ManageManwha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageManwhaActionPerformed(evt);
            }
        });
        MenuPNL.add(ManageManwha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 90, 40));

        LogoutAdmin.setText("Logout");
        LogoutAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogoutAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutAdminActionPerformed(evt);
            }
        });
        MenuPNL.add(LogoutAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 90, 30));

        jPanel1.add(MenuPNL, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 110, 380));

        SystemLogo.setBackground(new java.awt.Color(0, 0, 0));
        SystemLogo.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        SystemLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/images__2_-removebg-preview.png"))); // NOI18N
        SystemLogo.setMaximumSize(new java.awt.Dimension(60, 60));
        SystemLogo.setMinimumSize(new java.awt.Dimension(60, 60));
        jPanel1.add(SystemLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 90, 70));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SignUpHeader.setFont(new java.awt.Font("Palatino Linotype", 3, 24)); // NOI18N
        SignUpHeader.setText("Manage Manwhas");
        jPanel2.add(SignUpHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, -1, 30));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 520, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menu_book_40dp_1F1F1F_FILL0_wght400_GRAD0_opsz40.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 40, 30));

        adminManwhaTable.setBackground(new java.awt.Color(0, 0, 0));
        adminManwhaTable.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        adminManwhaTable.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        adminManwhaTable.setForeground(new java.awt.Color(255, 255, 255));
        adminManwhaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Title", "Genre", "Author", "Status"
            }
        ));
        jScrollPane1.setViewportView(adminManwhaTable);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 550, 350));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 550, 380));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 760, 20));

        Searchb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchbActionPerformed(evt);
            }
        });
        jPanel1.add(Searchb, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, 100, 30));

        refrsh.setBackground(new java.awt.Color(255, 255, 255));
        refrsh.setForeground(new java.awt.Color(255, 255, 255));
        refrsh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/refreshwhite.png"))); // NOI18N
        refrsh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refrshActionPerformed(evt);
            }
        });
        jPanel1.add(refrsh, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 30, 20));

        ManageChapters.setText("Chapters");
        ManageChapters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageChaptersActionPerformed(evt);
            }
        });
        jPanel1.add(ManageChapters, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 80, 30));

        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        jPanel1.add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 70, 30));

        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        jPanel1.add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 70, 30));

        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        jPanel1.add(Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 70, 30));

        btnSearch1.setBackground(new java.awt.Color(255, 255, 255));
        btnSearch1.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search.png"))); // NOI18N
        btnSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnSearch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, 30, 30));

        jFrame1.getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 480));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SystemLogo1.setBackground(new java.awt.Color(0, 0, 0));
        SystemLogo1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        SystemLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/images__2_-removebg-preview.png"))); // NOI18N
        SystemLogo1.setMaximumSize(new java.awt.Dimension(60, 60));
        SystemLogo1.setMinimumSize(new java.awt.Dimension(60, 60));
        jPanel3.add(SystemLogo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 90, 70));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 640, 20));

        ManageChaptersTable.setBackground(new java.awt.Color(0, 0, 0));
        ManageChaptersTable.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ManageChaptersTable.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        ManageChaptersTable.setForeground(new java.awt.Color(255, 255, 255));
        ManageChaptersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Chapter No.", "Title", "LastFree"
            }
        ));
        jScrollPane2.setViewportView(ManageChaptersTable);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 640, 240));

        Deletech.setText("Delete Chapter/s");
        Deletech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletechActionPerformed(evt);
            }
        });
        jPanel4.add(Deletech, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 120, 30));

        managepage.setText("Manage Pages");
        managepage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managepageActionPerformed(evt);
            }
        });
        jPanel4.add(managepage, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 130, 30));

        Addch1.setText("Add Chapter/s");
        Addch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Addch1ActionPerformed(evt);
            }
        });
        jPanel4.add(Addch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 120, 30));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 640, 330));
        jPanel3.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 760, 20));

        SearchBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBarActionPerformed(evt);
            }
        });
        jPanel3.add(SearchBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, 100, 30));

        refrsh1.setBackground(new java.awt.Color(0, 0, 0));
        refrsh1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/refreshwhite.png"))); // NOI18N
        refrsh1.setOpaque(false);
        refrsh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refrsh1ActionPerformed(evt);
            }
        });
        jPanel3.add(refrsh1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 30, 20));

        ManageChapterTitle.setFont(new java.awt.Font("Palatino Linotype", 3, 24)); // NOI18N
        ManageChapterTitle.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(ManageChapterTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 220, 30));

        Closebut.setText("CLOSE");
        Closebut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClosebutActionPerformed(evt);
            }
        });
        jPanel3.add(Closebut, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 430, 120, 30));

        ManageChaptesrHeader.setFont(new java.awt.Font("Palatino Linotype", 3, 24)); // NOI18N
        ManageChaptesrHeader.setForeground(new java.awt.Color(255, 255, 255));
        ManageChaptesrHeader.setText("Manage Chapters -");
        jPanel3.add(ManageChaptesrHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 730, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OverviewAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OverviewAdminActionPerformed
        
    }//GEN-LAST:event_OverviewAdminActionPerformed

    private void UsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsersActionPerformed
        
    }//GEN-LAST:event_UsersActionPerformed

    private void ManageManwhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageManwhaActionPerformed

    }//GEN-LAST:event_ManageManwhaActionPerformed

    private void LogoutAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutAdminActionPerformed
        if (JOptionPane.showConfirmDialog(this,
            "Are you sure you want to logout?",
            "Confirm Logout",
            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {

        new login().setVisible(true);
        this.dispose();
        }
    }//GEN-LAST:event_LogoutAdminActionPerformed

    private void SearchbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchbActionPerformed
       
        
    }//GEN-LAST:event_SearchbActionPerformed

    private void refrshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refrshActionPerformed
        
    }//GEN-LAST:event_refrshActionPerformed

    private void ManageChaptersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageChaptersActionPerformed

    }//GEN-LAST:event_ManageChaptersActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        
    }//GEN-LAST:event_DeleteActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
    
    }//GEN-LAST:event_UpdateActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed

    }//GEN-LAST:event_AddActionPerformed

    private void btnSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearch1ActionPerformed

    private void refrsh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refrsh1ActionPerformed
SearchBar.setText("");
loadChapters();        
    }//GEN-LAST:event_refrsh1ActionPerformed

    private void managepageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managepageActionPerformed
int row = ManageChaptersTable.getSelectedRow();
if (row == -1) {
    JOptionPane.showMessageDialog(this, "Select a chapter first!");
    return;
}

String chapterNo = ManageChaptersTable.getValueAt(row, 0).toString();
String chapterTitle = ManageChaptersTable.getValueAt(row, 1).toString();

try (java.sql.Connection conn = config.connectDB();
     java.sql.PreparedStatement pst = conn.prepareStatement(
         "SELECT chapter_id FROM tbl_chapters WHERE m_id=? AND chapter_no=?")) {

    pst.setInt(1, manwhaId);
    pst.setString(2, chapterNo);
    java.sql.ResultSet rs = pst.executeQuery();

    if (rs.next()) {
        int chapterId = rs.getInt("chapter_id");
        new ManagePages(chapterId, chapterTitle).setVisible(true);
    }

} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
}
    }//GEN-LAST:event_managepageActionPerformed

    private void DeletechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletechActionPerformed
     int row = ManageChaptersTable.getSelectedRow();
if (row == -1) {
    JOptionPane.showMessageDialog(this, "Select a chapter first!");
    return;
}

int confirm = JOptionPane.showConfirmDialog(this,
    "Delete this chapter and all its pages?", "Confirm",
    JOptionPane.YES_NO_OPTION);

if (confirm == JOptionPane.YES_OPTION) {
    String chapterNo = ManageChaptersTable.getValueAt(row, 0).toString();
    
    try (java.sql.Connection conn = config.connectDB()) {
        java.sql.PreparedStatement getChapter = conn.prepareStatement(
            "SELECT chapter_id FROM tbl_chapters WHERE m_id=? AND chapter_no=?");
        getChapter.setInt(1, manwhaId);
        getChapter.setString(2, chapterNo);
        java.sql.ResultSet rs = getChapter.executeQuery();
        
        if (rs.next()) {
            int chapterId = rs.getInt("chapter_id");
            
            java.sql.PreparedStatement delPages = conn.prepareStatement(
                "DELETE FROM tbl_pages WHERE chapter_id=?");
            delPages.setInt(1, chapterId);
            delPages.executeUpdate();
            
            java.sql.PreparedStatement delChapter = conn.prepareStatement(
                "DELETE FROM tbl_chapters WHERE chapter_id=?");
            delChapter.setInt(1, chapterId);
            delChapter.executeUpdate();
        }
        
        JOptionPane.showMessageDialog(this, "Chapter deleted!");
        loadChapters();
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
}
    }//GEN-LAST:event_DeletechActionPerformed

    private void ClosebutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClosebutActionPerformed
this.dispose();
    }//GEN-LAST:event_ClosebutActionPerformed

    private void Addch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Addch1ActionPerformed
        String chapterNo = JOptionPane.showInputDialog(this, "Enter Chapter Number:");
if (chapterNo == null || chapterNo.trim().isEmpty()) return;

String chapterTitle = JOptionPane.showInputDialog(this, "Enter Chapter Title:");
if (chapterTitle == null || chapterTitle.trim().isEmpty()) return;

int lastFree = JOptionPane.showConfirmDialog(this,
    "Is this the last free chapter?", "Last Free",
    JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION ? 1 : 0;

try (java.sql.Connection conn = config.connectDB();
     java.sql.PreparedStatement pst = conn.prepareStatement(
         "INSERT INTO tbl_chapters (m_id, chapter_no, chapter_title, last_free) VALUES (?,?,?,?)")) {

    pst.setInt(1, manwhaId);
    pst.setString(2, chapterNo.trim());
    pst.setString(3, chapterTitle.trim());
    pst.setInt(4, lastFree);
    pst.executeUpdate();

    JOptionPane.showMessageDialog(this, "Chapter added!");
    loadChapters();

} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
}
    }//GEN-LAST:event_Addch1ActionPerformed

    private void SearchBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBarActionPerformed

    }//GEN-LAST:event_SearchBarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageChapters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageChapters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageChapters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageChapters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               new ManageChapters(0, "").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Addch1;
    private javax.swing.JButton Closebut;
    private javax.swing.JButton Delete;
    private javax.swing.JButton Deletech;
    private javax.swing.JButton LogoutAdmin;
    private javax.swing.JLabel ManageChapterTitle;
    private javax.swing.JButton ManageChapters;
    private javax.swing.JTable ManageChaptersTable;
    private javax.swing.JLabel ManageChaptesrHeader;
    private javax.swing.JButton ManageManwha;
    private javax.swing.JPanel MenuPNL;
    private javax.swing.JButton OverviewAdmin;
    private javax.swing.JTextField SearchBar;
    private javax.swing.JTextField Searchb;
    private javax.swing.JLabel SignUpHeader;
    private javax.swing.JLabel SystemLogo;
    private javax.swing.JLabel SystemLogo1;
    private javax.swing.JButton Update;
    private javax.swing.JButton Users;
    private javax.swing.JTable adminManwhaTable;
    private javax.swing.JButton btnSearch1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JButton managepage;
    private javax.swing.JButton refrsh;
    private javax.swing.JButton refrsh1;
    // End of variables declaration//GEN-END:variables
}
