/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CRUDadmin;

import config.config;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Resty
 */
public class ManagePages extends javax.swing.JFrame {

 private int chapterId;
private String chapterTitle;

    public ManagePages(int chapterId, String chapterTitle) {
    this.chapterId = chapterId;
    this.chapterTitle = chapterTitle;
    initComponents();
    ChapterTitle.setText(chapterTitle);
    loadPages();
}
    
    private void loadPages() {
    try (java.sql.Connection conn = config.connectDB();
         java.sql.PreparedStatement pst = conn.prepareStatement(
             "SELECT page_no, image FROM tbl_pages WHERE chapter_id=? ORDER BY CAST(page_no AS INTEGER)")) {

        pst.setInt(1, chapterId);
        java.sql.ResultSet rs = pst.executeQuery();

        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(
            new String[]{"Page No", "Image Path"}, 0);

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("page_no"),
                rs.getString("image")
            });
        }
        ManagePageTable.setModel(model);
        ManagePageTable.setDefaultEditor(Object.class, null);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        SystemLogo1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        ManagePageTable = new javax.swing.JTable();
        Deletepg = new javax.swing.JButton();
        Addpg = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        SearchBar = new javax.swing.JTextField();
        refrsh1 = new javax.swing.JButton();
        ChapterTitle = new javax.swing.JLabel();
        Closebut = new javax.swing.JButton();
        ManagePagesHeader = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SystemLogo1.setBackground(new java.awt.Color(0, 0, 0));
        SystemLogo1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        SystemLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/images__2_-removebg-preview.png"))); // NOI18N
        SystemLogo1.setMaximumSize(new java.awt.Dimension(60, 60));
        SystemLogo1.setMinimumSize(new java.awt.Dimension(60, 60));
        jPanel1.add(SystemLogo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 90, 70));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 640, 20));

        ManagePageTable.setBackground(new java.awt.Color(0, 0, 0));
        ManagePageTable.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ManagePageTable.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        ManagePageTable.setForeground(new java.awt.Color(255, 255, 255));
        ManagePageTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "PageNo.", "Image"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(ManagePageTable);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 640, 240));

        Deletepg.setText("Delete Page/s");
        Deletepg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletepgActionPerformed(evt);
            }
        });
        jPanel4.add(Deletepg, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 120, 30));

        Addpg.setText("Add Page/s");
        Addpg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddpgActionPerformed(evt);
            }
        });
        jPanel4.add(Addpg, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 120, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 640, 330));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 760, 20));

        SearchBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBarActionPerformed(evt);
            }
        });
        jPanel1.add(SearchBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, 100, 30));

        refrsh1.setBackground(new java.awt.Color(0, 0, 0));
        refrsh1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/refreshwhite.png"))); // NOI18N
        refrsh1.setOpaque(false);
        refrsh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refrsh1ActionPerformed(evt);
            }
        });
        jPanel1.add(refrsh1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 30, 20));

        ChapterTitle.setFont(new java.awt.Font("Palatino Linotype", 3, 24)); // NOI18N
        ChapterTitle.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(ChapterTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 220, 30));

        Closebut.setText("CLOSE");
        Closebut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClosebutActionPerformed(evt);
            }
        });
        jPanel1.add(Closebut, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 430, 120, 30));

        ManagePagesHeader.setFont(new java.awt.Font("Palatino Linotype", 3, 24)); // NOI18N
        ManagePagesHeader.setForeground(new java.awt.Color(255, 255, 255));
        ManagePagesHeader.setText("Manage Pages -");
        jPanel1.add(ManagePagesHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 730, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DeletepgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletepgActionPerformed
      int row = ManagePageTable.getSelectedRow();
if (row == -1) {
    JOptionPane.showMessageDialog(this, "Select a page first!");
    return;
}

int confirm = JOptionPane.showConfirmDialog(this,
    "Delete this page?", "Confirm", JOptionPane.YES_NO_OPTION);

if (confirm == JOptionPane.YES_OPTION) {
    String pageNo = ManagePageTable.getValueAt(row, 0).toString();
    
    try (java.sql.Connection conn = config.connectDB();
         java.sql.PreparedStatement pst = conn.prepareStatement(
             "DELETE FROM tbl_pages WHERE chapter_id=? AND page_no=?")) {
        pst.setInt(1, chapterId);
        pst.setString(2, pageNo);
        pst.executeUpdate();
        JOptionPane.showMessageDialog(this, "Page deleted!");
        loadPages();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
}
    }//GEN-LAST:event_DeletepgActionPerformed

    private void AddpgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddpgActionPerformed
      JFileChooser chooser = new JFileChooser();
chooser.setMultiSelectionEnabled(true);
int result = chooser.showOpenDialog(this);

if (result == JFileChooser.APPROVE_OPTION) {
    java.io.File[] files = chooser.getSelectedFiles();
    
    // get current max page no
    int maxPage = 0;
    try (java.sql.Connection conn = config.connectDB();
         java.sql.PreparedStatement pst = conn.prepareStatement(
             "SELECT MAX(CAST(page_no AS INTEGER)) FROM tbl_pages WHERE chapter_id=?")) {
        pst.setInt(1, chapterId);
        java.sql.ResultSet rs = pst.executeQuery();
        if (rs.next() && rs.getString(1) != null) maxPage = rs.getInt(1);
    } catch (Exception e) { }

    try (java.sql.Connection conn = config.connectDB();
         java.sql.PreparedStatement pst = conn.prepareStatement(
             "INSERT INTO tbl_pages (chapter_id, page_no, image) VALUES (?,?,?)")) {

        for (int i = 0; i < files.length; i++) {
            pst.setInt(1, chapterId);
            pst.setString(2, String.valueOf(maxPage + i + 1));
            pst.setString(3, files[i].getAbsolutePath());
            pst.executeUpdate();
        }
        JOptionPane.showMessageDialog(this, files.length + " page/s added!");
        loadPages();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
}
    }//GEN-LAST:event_AddpgActionPerformed

    private void SearchBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBarActionPerformed

    }//GEN-LAST:event_SearchBarActionPerformed

    private void refrsh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refrsh1ActionPerformed
        SearchBar.setText("");
            loadPages();
    }//GEN-LAST:event_refrsh1ActionPerformed

    private void ClosebutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClosebutActionPerformed
        this.dispose();
    }//GEN-LAST:event_ClosebutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagePages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagePages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagePages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagePages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagePages(0, "").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addpg;
    private javax.swing.JLabel ChapterTitle;
    private javax.swing.JButton Closebut;
    private javax.swing.JButton Deletepg;
    private javax.swing.JTable ManagePageTable;
    private javax.swing.JLabel ManagePagesHeader;
    private javax.swing.JTextField SearchBar;
    private javax.swing.JLabel SystemLogo1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JButton refrsh1;
    // End of variables declaration//GEN-END:variables
}
