/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CRUDadmin;
  
import config.config;
import javax.swing.JOptionPane;

/**
 *
 * @author Resty
 */
public class Update extends javax.swing.JFrame {
      config cfg = new config();

    private int manwhaID; 
    

    /**
     * Creates new form Update
     */
   public Update(int id, String title, String genre, String author, String status) {
       
    initComponents();

    this.manwhaID = id;

    UpdTitle.setText(title);
    UpdGenre.setText(genre);
    UpdAuthor.setText(author);
    UpdStatus.setText(status);
}
   
public Update() {
    initComponents();
    
    getRootPane().setDefaultButton(Updatebtn);
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        AddHeader = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        UStatus = new javax.swing.JLabel();
        UTitle = new javax.swing.JLabel();
        UGenre = new javax.swing.JLabel();
        UAuthor = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        Updatebtn = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        UpdStatus = new javax.swing.JTextField();
        UpdTitle = new javax.swing.JTextField();
        UpdGenre = new javax.swing.JTextField();
        UpdAuthor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/manwhalegends.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 260, 220, 100));

        AddHeader.setFont(new java.awt.Font("Palatino Linotype", 3, 36)); // NOI18N
        AddHeader.setText("Update Manwha");
        jPanel1.add(AddHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, -1, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 560, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 560, 10));

        UStatus.setFont(new java.awt.Font("Palatino Linotype", 2, 18)); // NOI18N
        UStatus.setText("Status:");
        jPanel1.add(UStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        UTitle.setFont(new java.awt.Font("Palatino Linotype", 2, 18)); // NOI18N
        UTitle.setText("Title:");
        jPanel1.add(UTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        UGenre.setFont(new java.awt.Font("Palatino Linotype", 2, 18)); // NOI18N
        UGenre.setText("Genre:");
        jPanel1.add(UGenre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        UAuthor.setFont(new java.awt.Font("Palatino Linotype", 2, 18)); // NOI18N
        UAuthor.setText("Author:");
        jPanel1.add(UAuthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 70, 40));

        Updatebtn.setText("Update");
        Updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatebtnActionPerformed(evt);
            }
        });
        jPanel1.add(Updatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 70, 40));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 50, 10));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 50, 10));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 40, 10));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 60, 10));

        UpdStatus.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        UpdStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdStatusActionPerformed(evt);
            }
        });
        jPanel1.add(UpdStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 360, 30));

        UpdTitle.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        UpdTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdTitleActionPerformed(evt);
            }
        });
        jPanel1.add(UpdTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 360, 30));

        UpdGenre.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        UpdGenre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdGenreActionPerformed(evt);
            }
        });
        jPanel1.add(UpdGenre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 360, 30));

        UpdAuthor.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        UpdAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdAuthorActionPerformed(evt);
            }
        });
        jPanel1.add(UpdAuthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 360, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 360));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void UpdStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdStatusActionPerformed

    private void UpdTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdTitleActionPerformed

    private void UpdGenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdGenreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdGenreActionPerformed

    private void UpdAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdAuthorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdAuthorActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void UpdatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatebtnActionPerformed
String title = UpdTitle.getText();
String genre = UpdGenre.getText();
String author = UpdAuthor.getText();
String status = UpdStatus.getText();

if(title.isEmpty() || genre.isEmpty() || author.isEmpty() || status.isEmpty()){
    JOptionPane.showMessageDialog(this, "All fields are required!");
    return;
}

cfg.updateManwha(manwhaID, title, genre, author, status);

JOptionPane.showMessageDialog(this, "Manwha Updated Successfully!");

this.dispose();
    }//GEN-LAST:event_UpdatebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddHeader;
    private javax.swing.JLabel UAuthor;
    private javax.swing.JLabel UGenre;
    private javax.swing.JLabel UStatus;
    private javax.swing.JLabel UTitle;
    private javax.swing.JTextField UpdAuthor;
    private javax.swing.JTextField UpdGenre;
    private javax.swing.JTextField UpdStatus;
    private javax.swing.JTextField UpdTitle;
    private javax.swing.JButton Updatebtn;
    private javax.swing.JButton btnCancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    // End of variables declaration//GEN-END:variables
}
