/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ChaptersPages;

/**
 *
 * @author Resty
 */
public class Chapters extends javax.swing.JFrame {

    /**
     * Creates new form Chapters
     */
    private int manwhaId;
private int[] chapterIds = new int[6];

    public Chapters(int manwhaId) {
    this.manwhaId = manwhaId;
    initComponents();
    loadChapterDetails();
    loadChapters();
}
    
    private void loadChapterDetails() {
    try (java.sql.Connection conn = config.config.connectDB();
         java.sql.PreparedStatement pst = conn.prepareStatement(
             "SELECT title, author, status, image FROM tbl_manwha WHERE m_id=?")) {

        pst.setInt(1, manwhaId);
        java.sql.ResultSet rs = pst.executeQuery();

        if (rs.next()) {
            ManwhaT.setText(rs.getString("title"));
            ManwhaA.setText(rs.getString("author"));
            ManwhaS.setText(rs.getString("status"));

            String imagePath = rs.getString("image");
            if (imagePath != null && !imagePath.isEmpty()) {
                java.net.URL imgURL = getClass().getResource("/" + imagePath);
                if (imgURL != null) {
                    javax.swing.ImageIcon icon = new javax.swing.ImageIcon(imgURL);
                 java.awt.Image img = icon.getImage().getScaledInstance(
    ManwhaImageCover.getWidth(), ManwhaImageCover.getHeight(),
    java.awt.Image.SCALE_SMOOTH);
ManwhaImageCover.setIcon(new javax.swing.ImageIcon(img));
                }
            }
        }
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
}
    
    private void loadChapters() {
    javax.swing.JLabel[] chapterLabels = {chapter1, chapter2, chapter3, chapter4, chapter5, chapter6};
    javax.swing.JLabel[] statusLabels = {Free2, Free3, Free4, locked1, locked2, locked3};
    javax.swing.JPanel[] chapterPanels = {ch1pnl, ch2pnl, ch3pnl, ch4pnl, ch5pnl, ch6pnl};

    // hide all first
    for (int i = 0; i < 6; i++) {
        chapterPanels[i].setVisible(false);
    }

    try (java.sql.Connection conn = config.config.connectDB();
         java.sql.PreparedStatement pst = conn.prepareStatement(
             "SELECT chapter_id, chapter_no, last_free FROM tbl_chapters WHERE m_id=? ORDER BY CAST(chapter_no AS INTEGER) LIMIT 6")) {

        pst.setInt(1, manwhaId);
        java.sql.ResultSet rs = pst.executeQuery();

        java.util.List<int[]> rows = new java.util.ArrayList<>();
        int lastFreeIndex = 0;

        while (rs.next()) {
            rows.add(new int[]{
                rs.getInt("chapter_id"),
                rs.getInt("chapter_no"),
                rs.getInt("last_free")
            });
        }

        // find last free index
        for (int i = 0; i < rows.size(); i++) {
            if (rows.get(i)[2] == 1) lastFreeIndex = i;
        }

        for (int i = 0; i < rows.size(); i++) {
            chapterIds[i] = rows.get(i)[0];
            chapterLabels[i].setText("Chapter " + rows.get(i)[1]);
            chapterPanels[i].setVisible(true);

            if (i <= lastFreeIndex) {
                statusLabels[i].setText("Free");
                statusLabels[i].setForeground(new java.awt.Color(0, 200, 0));
                chapterLabels[i].setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                final int chapterId = chapterIds[i];
                final int chNo = rows.get(i)[1];
                chapterLabels[i].addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        new Pages(chapterId, chNo).setVisible(true);
                    }
                });
            } else {
                statusLabels[i].setText("Locked");
                statusLabels[i].setForeground(java.awt.Color.RED);
            }
        }

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        ChapterPanel = new javax.swing.JPanel();
        chapterform = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        Author = new javax.swing.JLabel();
        Status = new javax.swing.JLabel();
        Title1 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        Author1 = new javax.swing.JLabel();
        Status1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        ch3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        Ch2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        ch1 = new javax.swing.JLabel();
        ch4 = new javax.swing.JPanel();
        Ch4 = new javax.swing.JLabel();
        ch5 = new javax.swing.JPanel();
        Ch5 = new javax.swing.JLabel();
        ch6 = new javax.swing.JPanel();
        Ch6 = new javax.swing.JLabel();
        lock3 = new javax.swing.JLabel();
        Free1 = new javax.swing.JLabel();
        lock = new javax.swing.JLabel();
        lock2 = new javax.swing.JLabel();
        free3 = new javax.swing.JLabel();
        free2 = new javax.swing.JLabel();
        ManwhaCover = new javax.swing.JLabel();
        ChapterPanel1 = new javax.swing.JPanel();
        chapterform1 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        jSeparator17 = new javax.swing.JSeparator();
        jSeparator18 = new javax.swing.JSeparator();
        jSeparator19 = new javax.swing.JSeparator();
        PanelForTAS = new javax.swing.JPanel();
        Author2 = new javax.swing.JLabel();
        Status2 = new javax.swing.JLabel();
        ManwhaS = new javax.swing.JLabel();
        Title3 = new javax.swing.JLabel();
        ManwhaT = new javax.swing.JLabel();
        ManwhaA = new javax.swing.JLabel();
        jSeparator20 = new javax.swing.JSeparator();
        PanelForChapters = new javax.swing.JPanel();
        ch3pnl = new javax.swing.JPanel();
        chapter3 = new javax.swing.JLabel();
        ch2pnl = new javax.swing.JPanel();
        chapter2 = new javax.swing.JLabel();
        ch1pnl = new javax.swing.JPanel();
        chapter1 = new javax.swing.JLabel();
        ch4pnl = new javax.swing.JPanel();
        chapter4 = new javax.swing.JLabel();
        ch5pnl = new javax.swing.JPanel();
        chapter5 = new javax.swing.JLabel();
        ch6pnl = new javax.swing.JPanel();
        chapter6 = new javax.swing.JLabel();
        locked3 = new javax.swing.JLabel();
        Free2 = new javax.swing.JLabel();
        locked1 = new javax.swing.JLabel();
        locked2 = new javax.swing.JLabel();
        Free3 = new javax.swing.JLabel();
        Free4 = new javax.swing.JLabel();
        ManwhaImageCover = new javax.swing.JLabel();
        BackArr = new javax.swing.JLabel();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ChapterPanel.setBackground(new java.awt.Color(0, 0, 0));
        ChapterPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chapterform.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        chapterform.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 660, 20));
        chapterform.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 10, 20));
        chapterform.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 30, 20));
        chapterform.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 30, 20));
        chapterform.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 30, 20));
        chapterform.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 30, 20));
        chapterform.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 30, 20));
        chapterform.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 30, 20));
        chapterform.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 20, 20));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Author.setFont(new java.awt.Font("Palatino Linotype", 3, 24)); // NOI18N
        Author.setText("Author:");
        jPanel2.add(Author, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        Status.setFont(new java.awt.Font("Palatino Linotype", 3, 24)); // NOI18N
        Status.setText("Status:");
        jPanel2.add(Status, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        Title1.setFont(new java.awt.Font("Palatino Linotype", 3, 24)); // NOI18N
        Title1.setText("Title: ");
        jPanel2.add(Title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        chapterform.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 320, 200));
        chapterform.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 30, 20));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Author1.setFont(new java.awt.Font("Palatino Linotype", 3, 24)); // NOI18N
        jPanel3.add(Author1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        Status1.setFont(new java.awt.Font("Palatino Linotype", 3, 24)); // NOI18N
        jPanel3.add(Status1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, null));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ch3.setFont(new java.awt.Font("Palatino Linotype", 3, 22)); // NOI18N
        ch3.setForeground(new java.awt.Color(255, 255, 255));
        ch3.setText("Chapter 3");
        jPanel4.add(ch3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 110, 20));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 140, 40));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, null));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Ch2.setFont(new java.awt.Font("Palatino Linotype", 3, 22)); // NOI18N
        Ch2.setForeground(new java.awt.Color(255, 255, 255));
        Ch2.setText("Chapter 2");
        jPanel5.add(Ch2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 110, 20));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 140, 40));

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, null));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ch1.setFont(new java.awt.Font("Palatino Linotype", 3, 22)); // NOI18N
        ch1.setForeground(new java.awt.Color(255, 255, 255));
        ch1.setText("Chapter 1");
        jPanel6.add(ch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 110, 20));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 140, 40));

        ch4.setBackground(new java.awt.Color(0, 0, 0));
        ch4.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, null));
        ch4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Ch4.setFont(new java.awt.Font("Palatino Linotype", 3, 22)); // NOI18N
        Ch4.setForeground(new java.awt.Color(255, 255, 255));
        Ch4.setText("Chapter 4");
        ch4.add(Ch4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 110, 20));

        jPanel3.add(ch4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 140, 40));

        ch5.setBackground(new java.awt.Color(0, 0, 0));
        ch5.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, null));
        ch5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Ch5.setFont(new java.awt.Font("Palatino Linotype", 3, 22)); // NOI18N
        Ch5.setForeground(new java.awt.Color(255, 255, 255));
        Ch5.setText("Chapter 5");
        ch5.add(Ch5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 110, 20));

        jPanel3.add(ch5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 140, 40));

        ch6.setBackground(new java.awt.Color(0, 0, 0));
        ch6.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, null));
        ch6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Ch6.setFont(new java.awt.Font("Palatino Linotype", 3, 22)); // NOI18N
        Ch6.setForeground(new java.awt.Color(255, 255, 255));
        Ch6.setText("Chapter 6");
        ch6.add(Ch6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 110, 20));

        jPanel3.add(ch6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 140, 40));

        lock3.setFont(new java.awt.Font("Palatino Linotype", 3, 24)); // NOI18N
        lock3.setText("[Locked]");
        jPanel3.add(lock3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, -1, -1));

        Free1.setFont(new java.awt.Font("Palatino Linotype", 3, 24)); // NOI18N
        Free1.setText("[Free]");
        jPanel3.add(Free1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        lock.setFont(new java.awt.Font("Palatino Linotype", 3, 24)); // NOI18N
        lock.setText("[Locked]");
        jPanel3.add(lock, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, -1, -1));

        lock2.setFont(new java.awt.Font("Palatino Linotype", 3, 24)); // NOI18N
        lock2.setText("[Locked]");
        jPanel3.add(lock2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, -1, -1));

        free3.setFont(new java.awt.Font("Palatino Linotype", 3, 24)); // NOI18N
        free3.setText("[Free]");
        jPanel3.add(free3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, -1, -1));

        free2.setFont(new java.awt.Font("Palatino Linotype", 3, 24)); // NOI18N
        free2.setText("[Free]");
        jPanel3.add(free2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));

        chapterform.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 640, 160));
        chapterform.add(ManwhaCover, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 310, 190));

        ChapterPanel.add(chapterform, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 660, 400));

        jFrame1.getContentPane().add(ChapterPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 700, 420));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ChapterPanel1.setBackground(new java.awt.Color(0, 0, 0));
        ChapterPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chapterform1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        chapterform1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 660, 20));
        chapterform1.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 10, 20));
        chapterform1.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 30, 20));
        chapterform1.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 30, 20));
        chapterform1.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 30, 20));
        chapterform1.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 30, 20));
        chapterform1.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 30, 20));
        chapterform1.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 30, 20));
        chapterform1.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 20, 20));

        PanelForTAS.setBackground(new java.awt.Color(255, 255, 255));
        PanelForTAS.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        PanelForTAS.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Author2.setFont(new java.awt.Font("Palatino Linotype", 3, 24)); // NOI18N
        Author2.setText("Author:");
        PanelForTAS.add(Author2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        Status2.setFont(new java.awt.Font("Palatino Linotype", 3, 24)); // NOI18N
        Status2.setText("Status:");
        PanelForTAS.add(Status2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        ManwhaS.setFont(new java.awt.Font("Palatino Linotype", 3, 18)); // NOI18N
        PanelForTAS.add(ManwhaS, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 210, 30));

        Title3.setFont(new java.awt.Font("Palatino Linotype", 3, 24)); // NOI18N
        Title3.setText("Title: ");
        PanelForTAS.add(Title3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        ManwhaT.setFont(new java.awt.Font("Palatino Linotype", 3, 18)); // NOI18N
        PanelForTAS.add(ManwhaT, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 230, 30));

        ManwhaA.setFont(new java.awt.Font("Palatino Linotype", 3, 18)); // NOI18N
        PanelForTAS.add(ManwhaA, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 210, 30));

        chapterform1.add(PanelForTAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 320, 200));
        chapterform1.add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 30, 20));

        PanelForChapters.setBackground(new java.awt.Color(255, 255, 255));
        PanelForChapters.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        PanelForChapters.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ch3pnl.setBackground(new java.awt.Color(0, 0, 0));
        ch3pnl.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, null));
        ch3pnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chapter3.setFont(new java.awt.Font("Palatino Linotype", 3, 22)); // NOI18N
        chapter3.setForeground(new java.awt.Color(255, 255, 255));
        chapter3.setText("Chapter 3");
        chapter3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ch3pnl.add(chapter3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 110, 20));

        PanelForChapters.add(ch3pnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 140, 40));

        ch2pnl.setBackground(new java.awt.Color(0, 0, 0));
        ch2pnl.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, null));
        ch2pnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chapter2.setFont(new java.awt.Font("Palatino Linotype", 3, 22)); // NOI18N
        chapter2.setForeground(new java.awt.Color(255, 255, 255));
        chapter2.setText("Chapter 2");
        chapter2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ch2pnl.add(chapter2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 110, 20));

        PanelForChapters.add(ch2pnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 140, 40));

        ch1pnl.setBackground(new java.awt.Color(0, 0, 0));
        ch1pnl.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, null));
        ch1pnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chapter1.setFont(new java.awt.Font("Palatino Linotype", 3, 22)); // NOI18N
        chapter1.setForeground(new java.awt.Color(255, 255, 255));
        chapter1.setText("Chapter 1");
        chapter1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ch1pnl.add(chapter1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 110, 20));

        PanelForChapters.add(ch1pnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 140, 40));

        ch4pnl.setBackground(new java.awt.Color(0, 0, 0));
        ch4pnl.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, null));
        ch4pnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chapter4.setFont(new java.awt.Font("Palatino Linotype", 3, 22)); // NOI18N
        chapter4.setForeground(new java.awt.Color(255, 255, 255));
        chapter4.setText("Chapter 4");
        chapter4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ch4pnl.add(chapter4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 110, 20));

        PanelForChapters.add(ch4pnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 140, 40));

        ch5pnl.setBackground(new java.awt.Color(0, 0, 0));
        ch5pnl.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, null));
        ch5pnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chapter5.setFont(new java.awt.Font("Palatino Linotype", 3, 22)); // NOI18N
        chapter5.setForeground(new java.awt.Color(255, 255, 255));
        chapter5.setText("Chapter 5");
        chapter5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ch5pnl.add(chapter5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 110, 20));

        PanelForChapters.add(ch5pnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 140, 40));

        ch6pnl.setBackground(new java.awt.Color(0, 0, 0));
        ch6pnl.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, null));
        ch6pnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chapter6.setFont(new java.awt.Font("Palatino Linotype", 3, 22)); // NOI18N
        chapter6.setForeground(new java.awt.Color(255, 255, 255));
        chapter6.setText("Chapter 6");
        chapter6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ch6pnl.add(chapter6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 110, 20));

        PanelForChapters.add(ch6pnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 140, 40));

        locked3.setFont(new java.awt.Font("Palatino Linotype", 3, 24)); // NOI18N
        locked3.setText("[Locked]");
        PanelForChapters.add(locked3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, -1, -1));

        Free2.setFont(new java.awt.Font("Palatino Linotype", 3, 24)); // NOI18N
        Free2.setText("[Free]");
        PanelForChapters.add(Free2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        locked1.setFont(new java.awt.Font("Palatino Linotype", 3, 24)); // NOI18N
        locked1.setText("[Locked]");
        PanelForChapters.add(locked1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, -1, -1));

        locked2.setFont(new java.awt.Font("Palatino Linotype", 3, 24)); // NOI18N
        locked2.setText("[Locked]");
        PanelForChapters.add(locked2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, -1, -1));

        Free3.setFont(new java.awt.Font("Palatino Linotype", 3, 24)); // NOI18N
        Free3.setText("[Free]");
        PanelForChapters.add(Free3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, -1, -1));

        Free4.setFont(new java.awt.Font("Palatino Linotype", 3, 24)); // NOI18N
        Free4.setText("[Free]");
        PanelForChapters.add(Free4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));

        chapterform1.add(PanelForChapters, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 640, 160));
        chapterform1.add(ManwhaImageCover, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 310, 190));

        ChapterPanel1.add(chapterform1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 660, 400));

        BackArr.setForeground(new java.awt.Color(255, 255, 255));
        BackArr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/arrow.jpg"))); // NOI18N
        BackArr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BackArr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackArrMouseClicked(evt);
            }
        });
        ChapterPanel1.add(BackArr, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 20, 20));

        getContentPane().add(ChapterPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 710, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackArrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackArrMouseClicked
      this.dispose();
    }//GEN-LAST:event_BackArrMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Chapters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Chapters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Chapters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chapters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Chapters(0).setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Author;
    private javax.swing.JLabel Author1;
    private javax.swing.JLabel Author2;
    private javax.swing.JLabel BackArr;
    private javax.swing.JLabel Ch2;
    private javax.swing.JLabel Ch4;
    private javax.swing.JLabel Ch5;
    private javax.swing.JLabel Ch6;
    private javax.swing.JPanel ChapterPanel;
    private javax.swing.JPanel ChapterPanel1;
    private javax.swing.JLabel Free1;
    private javax.swing.JLabel Free2;
    private javax.swing.JLabel Free3;
    private javax.swing.JLabel Free4;
    private javax.swing.JLabel ManwhaA;
    private javax.swing.JLabel ManwhaCover;
    private javax.swing.JLabel ManwhaImageCover;
    private javax.swing.JLabel ManwhaS;
    private javax.swing.JLabel ManwhaT;
    private javax.swing.JPanel PanelForChapters;
    private javax.swing.JPanel PanelForTAS;
    private javax.swing.JLabel Status;
    private javax.swing.JLabel Status1;
    private javax.swing.JLabel Status2;
    private javax.swing.JLabel Title1;
    private javax.swing.JLabel Title3;
    private javax.swing.JLabel ch1;
    private javax.swing.JPanel ch1pnl;
    private javax.swing.JPanel ch2pnl;
    private javax.swing.JLabel ch3;
    private javax.swing.JPanel ch3pnl;
    private javax.swing.JPanel ch4;
    private javax.swing.JPanel ch4pnl;
    private javax.swing.JPanel ch5;
    private javax.swing.JPanel ch5pnl;
    private javax.swing.JPanel ch6;
    private javax.swing.JPanel ch6pnl;
    private javax.swing.JLabel chapter1;
    private javax.swing.JLabel chapter2;
    private javax.swing.JLabel chapter3;
    private javax.swing.JLabel chapter4;
    private javax.swing.JLabel chapter5;
    private javax.swing.JLabel chapter6;
    private javax.swing.JPanel chapterform;
    private javax.swing.JPanel chapterform1;
    private javax.swing.JLabel free2;
    private javax.swing.JLabel free3;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lock;
    private javax.swing.JLabel lock2;
    private javax.swing.JLabel lock3;
    private javax.swing.JLabel locked1;
    private javax.swing.JLabel locked2;
    private javax.swing.JLabel locked3;
    // End of variables declaration//GEN-END:variables
}
