/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ChaptersPages;

/**
 *
 * @author Resty
 */
public class Pages extends javax.swing.JFrame {

    /**
     * Creates new form Pages
     */
    private int chapterId;
private int chapterNo;

    public Pages(int chapterId, int chapterNo) {
    this.chapterId = chapterId;
    this.chapterNo = chapterNo;
    initComponents();
    chapterno.setText(String.valueOf(chapterNo));
    ChapterHeader.setText("Chapter " + chapterNo);
    loadPages();
}
    
    private void loadPages() {
    javax.swing.JPanel imagePanel = new javax.swing.JPanel();
    imagePanel.setLayout(new javax.swing.BoxLayout(imagePanel, javax.swing.BoxLayout.Y_AXIS));
    imagePanel.setBackground(java.awt.Color.BLACK);

    try (java.sql.Connection conn = config.config.connectDB();
         java.sql.PreparedStatement pst = conn.prepareStatement(
             "SELECT image FROM tbl_pages WHERE chapter_id=? ORDER BY CAST(page_no AS INTEGER)")) {

        pst.setInt(1, chapterId);
        java.sql.ResultSet rs = pst.executeQuery();

        while (rs.next()) {
            String imagePath = rs.getString("image");
            javax.swing.ImageIcon icon = new javax.swing.ImageIcon(imagePath);
            java.awt.Image img = icon.getImage().getScaledInstance(
                450, -1, java.awt.Image.SCALE_SMOOTH);
            javax.swing.JLabel pageLabel = new javax.swing.JLabel(new javax.swing.ImageIcon(img));
            pageLabel.setAlignmentX(java.awt.Component.CENTER_ALIGNMENT);
            imagePanel.add(pageLabel);
            imagePanel.add(javax.swing.Box.createRigidArea(new java.awt.Dimension(0, 5)));
        }

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }

    jScrollPane1.setViewportView(imagePanel);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ChapterPanel = new javax.swing.JPanel();
        chapterform = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        BackButt = new javax.swing.JPanel();
        Backbut = new javax.swing.JLabel();
        chapterno = new javax.swing.JLabel();
        ChapterHeader = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ChapterPanel.setBackground(new java.awt.Color(0, 0, 0));
        ChapterPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chapterform.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        chapterform.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 690, 10));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 570));

        chapterform.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 470, 570));

        BackButt.setBackground(new java.awt.Color(0, 0, 0));
        BackButt.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, null));
        BackButt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BackButt.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        BackButt.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Backbut.setFont(new java.awt.Font("Palatino Linotype", 3, 14)); // NOI18N
        Backbut.setForeground(new java.awt.Color(255, 255, 255));
        Backbut.setText("BACK");
        Backbut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackbutMouseClicked(evt);
            }
        });
        BackButt.add(Backbut, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 20));

        chapterform.add(BackButt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 60, 30));

        chapterno.setBackground(new java.awt.Color(0, 0, 0));
        chapterno.setFont(new java.awt.Font("Palatino Linotype", 3, 14)); // NOI18N
        chapterform.add(chapterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 60, 20));

        ChapterHeader.setBackground(new java.awt.Color(0, 0, 0));
        ChapterHeader.setFont(new java.awt.Font("Palatino Linotype", 3, 14)); // NOI18N
        ChapterHeader.setText("Chapter  ");
        chapterform.add(ChapterHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 60, 20));

        ChapterPanel.add(chapterform, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 600, 610));

        getContentPane().add(ChapterPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 650, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackbutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackbutMouseClicked
       this.dispose();
    }//GEN-LAST:event_BackbutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               new Pages(0, 0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackButt;
    private javax.swing.JLabel Backbut;
    private javax.swing.JLabel ChapterHeader;
    private javax.swing.JPanel ChapterPanel;
    private javax.swing.JPanel chapterform;
    private javax.swing.JLabel chapterno;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
